---
title: "Taylor Swift (Soon-to-be Kelce)"
subtitle: "Plot2"
format: html
editor: visual
---

```{r}
#| label: load-pkgs
#| message: false

library(tidyverse)
library(ggrepel)
```

```{r}
#| label: load-data
#| message: false

taylor_album_songs <- readr::read_csv('data/taylor_album_songs.csv', show_col_types = FALSE)
taylor_all_songs <- readr::read_csv('data/taylor_all_songs.csv', show_col_types = FALSE)
taylor_albums <- readr::read_csv('data/taylor_albums.csv', show_col_types = FALSE)
```

```{r}
#| label: create_dataframe_for_plot2a

taylor_albums_stats <- taylor_all_songs |>
  drop_na(energy, valence) |>
  group_by(album_name) |>
  summarise(
    album_energy = mean(energy),
    album_valence = mean(valence)
  )

taylor_albums_plot2a <- merge(taylor_albums, taylor_albums_stats)

taylor_albums_plot2a <- taylor_albums_plot2a |>
  pivot_longer(
    cols = c("album_energy", "album_valence"),
    names_to = "song_attribute",
    values_to = "attribute_value"
  ) |>
  mutate(
    song_attribute = fct_recode(song_attribute, "energy" = "album_energy", "valence" = "album_valence"),
    album_name = factor(album_name, 
                        levels = c("Midnights",  "evermore", "folklore",
                                   "Lover", "reputation", "1989", 
                                   "Red", "Speak Now", 
                                   "Fearless (Taylor's Version)", 
                                   "Fearless", "Taylor Swift", 
                                   "The Taylor Swift Holiday Collection",
                                   "Red (Taylor's Version)"))
  )

```

```{r}
#| label: experimental_plot

# ggplot(taylor_albums_plot2a, aes(x = album_release)) +
#   geom_point(aes(y = album_energy), color = "red") +
#   geom_point(aes(y = album_danceability), color = "blue") +
#   geom_point(aes(y = album_speechiness), color = "green") +
#   geom_point(aes(y = album_valence), color = "purple") +
#   geom_line(aes(y = album_energy), color = "red") +
#   geom_line(aes(y = album_danceability), color = "blue") +
#   geom_line(aes(y = album_speechiness), color = "green") +
#   geom_line(aes(y = album_valence), color = "purple") +
#   geom_smooth(aes(y = album_energy), method = "lm", se = FALSE, color = "pink") +
#   geom_smooth(aes(y = album_danceability), method = "lm", se = FALSE, color = "pink") +
#   geom_smooth(aes(y = album_speechiness), method = "lm", se = FALSE, color = "pink") +
#   geom_smooth(aes(y = album_valence), method = "lm", se = FALSE, color = "pink")
```

```{r fig.height = 8, fig.width = 11}
#| label: highlight_energy_plot

ggplot(taylor_albums_plot2a, aes(x = album_release)) +
  geom_line(aes(y = attribute_value), color = "#4D4D4D", size = 2) +
  geom_point(aes(y = attribute_value, color = album_name), size = 7, shape = 18) +
  geom_smooth(aes(y = attribute_value), method = "lm", se = FALSE, color = "#ff00ff60", size =2, linetype = "dashed") +
  geom_label_repel(aes(y = attribute_value, label = album_name, fill = album_name), color = "white", size = 3, 
                   nudge_y = 0.1, nudge_x = 100) +
  scale_y_continuous(breaks = seq(0.0, 1.0, by = 0.1), limits = c(0, 1)) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  scale_color_manual(values = c("#A26A5B", "#ACA38D", "#4D4D4D", "#DEA9C9", 
                               "#0A0A0A", "#7B96AF", "#982F47", "#704073", 
                               "#5F4A30", "#BD9365", "#4497BA", "#BA372E", "#903F31")) +
  scale_fill_manual(values = c("#A26A5B", "#ACA38D", "#4D4D4D", "#DEA9C9", 
                               "#0A0A0A", "#7B96AF", "#982F47", "#704073", 
                               "#5F4A30", "#BD9365", "#4497BA", "#BA372E", "#903F31")
  ) +
  labs(
    title = "Taylor Swift album attributes over time",
    x = "Album Release Date"
  ) +
  theme(
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
    axis.title.x = element_text(vjust = -1, size = 12),
    strip.text = element_text(size = 12)
  ) +
  facet_wrap(~song_attribute, ncol = 1, labeller = 
               labeller(song_attribute = c(energy = "Attribute: Energy", valence = "Attribute: Valence"))
  )

```

```{r}
#| label: data-wrangle-plot2b

#Albums we want to consider for plot 2b (only albums in Tidy Data with original & re-released)
original_and_rereleased_albums <- c("Red", "Red (Taylor's Version)", "Fearless", "Fearless (Taylor's Version)")

#Wrangling the data for plot 2b
plot2b_data <- subset(taylor_albums, album_name %in% original_and_rereleased_albums) |>
  mutate(user_score = user_score*10, 
         taylor_owned = ifelse(grepl("Taylor's Version", album_name), "Taylor's Version", "Scooter Owned"), 
         album = case_when(grepl("Red", album_name) ~ "Red", 
                           grepl("Fearless", album_name) ~ "Fearless", 
                           TRUE ~ "" )) |>
  select(album, metacritic_score, user_score, taylor_owned) 

#Pivoting longer to be able to put score on y-axis for plot 2b
plot2b_data <- plot2b_data |>
  pivot_longer(
    cols = c("metacritic_score", "user_score"), 
         names_to = "score_type", 
         values_to = "score") |>
  mutate(
    score_type = fct_recode(score_type, "metacritic" = "metacritic_score", "user" = "user_score")
  )


```

```{r}
#| label: plot2b-plotting

ggplot(plot2b_data, aes(x= score_type, y = score, fill = taylor_owned)) + 
  geom_col(position = "dodge") + 
  geom_text(aes(label = score), position = position_dodge(width = 0.9), vjust = -0.5, size = 3 ) +
  facet_wrap(~album)+ 
  scale_fill_manual(values = c("#4D4D4D", "#DEA9C9")) +
  theme_bw() +
  labs(
    title = "Original versus Taylor's Score Comparison",
    x = "Type of Score",
    y = "Score",
    fill = "Taylor's Version?",
    caption = "Source: Tidy Tuesday Data"
  )


```
