---
title: "Taylor Swift (Soon-to-be Kelce)"
subtitle: "Plot1"
format: html
editor: visual
---

```{r}
#| label: load-pkgs
#| message: false

library(tidyverse)
```

```{r}
#| label: load-data
#| message: false

taylor_album_songs <- readr::read_csv('data/taylor_album_songs.csv', show_col_types = FALSE)
taylor_all_songs <- readr::read_csv('data/taylor_all_songs.csv', show_col_types = FALSE)
taylor_albums <- readr::read_csv('data/taylor_albums.csv', show_col_types = FALSE)

taylor_streams <- readr::read_csv('data/Taylor_Swift_streams.csv', show_col_types = FALSE)
taylor_streams
```

```{r}
#| label: edit-data
#| message: false

taylor_all_songs <- taylor_all_songs |>
  drop_na(album_name) |>
  mutate(is_single = !(is.na(single_release)))

print(taylor_all_songs)

taylor_albums_energy <- taylor_all_songs |>
  drop_na(energy) |>
  group_by(album_name) |>
  summarise(album_energy = mean(energy))

taylor_singles_energy <- taylor_all_songs %>%
  filter(is_single == TRUE) %>%
  group_by(album_name) %>%
  summarise(singles_energy = mean(energy))

print(taylor_singles_energy)

taylor_albums_data <- merge(taylor_albums_energy, taylor_singles_energy)

taylor_albums_data <- taylor_albums_data |>
  pivot_longer(
    cols = c("album_energy", "singles_energy"),
    names_to = "song_type",
    values_to = "energy"
  ) |>
  mutate(
    song_type = fct_recode(song_type, "Album" = "album_energy", "Single" = "singles_energy")
  )

taylor_albums_data



```

```{r}
#| label: create-plot
#| message: false

# ggplot(taylor_albums_data, aes(x = album_name, y = singles_energy, fill = album_name)) +
#   geom_bar(stat = "identity") +
#   scale_fill_manual(values = c("#7B96AF", "#ACA38D", "#BD9365", "#5F4A30", 
#                                "#4D4D4D", "#DEA9C9", "#A26A5B", "#982F47", 
#                                "#0A0A0A", "#704073", "#4497BA")) +
#   #scale_y_continuous(breaks = seq(0, 1.0, 5), labels = seq(0, 1.0, 5)) + 
#   theme_bw() +
#   theme(axis.text.x = element_blank()) +
#   labs(title = "Taylor Swift Song Energy of Albums",
#        subtitle = "",
#        x = "Albums",
#        y = "Energy",
#        fill = "Album",
#        caption = "Source: Tidy Tuesday")

taylor_albums_data <- taylor_albums_data |>
  mutate(album_name = factor(album_name, levels = c("Midnights",  "evermore", "folklore", "Lover",
                                                    "reputation", "1989", "Red", "Speak Now",
                                                    "Fearless (Taylor's Version)", "Fearless", "Taylor Swift")))

# ggplot(taylor_albums_data, aes(x = energy, y = album_name, fill = song_type)) +
#   geom_col(position = "dodge") +
#   scale_fill_manual(values = c("#982F47", "#4497BA")) +
#   theme_bw() +
#   labs(
#     title = "Energy Values of Taylor Swift Albums",
#     x = "Albums",
#     y = "Energy",
#     fill = "Energy Type",
#     caption = "Source: Tidy Tuesday Data"
#   )

ggplot(taylor_albums_data, aes(x = album_name, y = energy, fill = album_name)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(energy, 2)), position = position_dodge(width = 0.9), vjust = -0.5, size = 2) +
  facet_wrap(~song_type) +
  scale_fill_manual(values = c("#A26A5B", "#ACA38D", "#4D4D4D", "#DEA9C9", 
                               "#0A0A0A", "#7B96AF", "#982F47", "#704073", 
                               "#5F4A30", "#BD9365", "#4497BA")) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  labs(
    title = "Energy Values of Taylor Swift Albums Versus Single Releases",
    subtitle = "Colored by Album",
    x = "Albums",
    y = "Energy",
    fill = "Album",
    caption = "Source: Tidy Tuesday Data"
  )
```

```{r}
#| label: create-plot2
#| message: false

ggplot(taylor_albums_data, aes(x = album_name, y = energy, fill = album_name)) +
  geom_point() +
  scale_fill_manual(values = c("#7B96AF", "#ACA38D", "#BD9365", "#5F4A30", 
                               "#4D4D4D", "#DEA9C9", "#A26A5B", "#982F47", 
                               "#0A0A0A", "#704073", "#4497BA")) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  labs(
    title = "Energy Values of Taylor Swift Albums",
    x = "Albums",
    y = "Energy",
    fill = "Energy Type",
    caption = "Source: Your Source"
  )
```

```{r}
#| label: ezra-chunk


```
